from litellm import completion
import config

SYSTEM_PROMPT = """You are a highly professional, human technical consultant negotiating a deal on WhatsApp.
CRITICAL RULES:
1. NEVER say you are an AI, a language model, or an assistant. Act entirely human.
2. Be conversational and natural. Answer their questions directly.
3. Keep your responses extremely short (1-2 sentences maximum). People text in short bursts on WhatsApp.
4. After answering their question, ask ONE simple, relevant question about their business (e.g. how they handle missed calls, bookings, or operations) to keep the conversation moving forward.
5. If client asks for a discount, explain: 'Our pricing covers itself with just one recovered lead a month.'"""

def generate_initial_message(ticket: dict) -> str:
    business = ticket.get("Business Name", "there")
    detail = ticket.get("Scraped Flaw/Detail", "")
    threshold = ticket.get("Minimum Price Floor", "")
    agent_role = ticket.get("AI Assigned Persona/Role", "")
    
    try:
        kb = open("../data/knowledgebase.txt").read()
    except FileNotFoundError:
        kb = "Automated CRM and booking software."
    
    import random
    angles = [
        "A warm, friendly greeting hoping they are having a good day, asking if they have a minute to chat.",
        "A polite check-in asking if it's a good time to talk for a brief moment.",
        "A casual 'Hello! Hope you're doing well, can we chat for a bit?' style message.",
        "A simple greeting wishing them a great day and asking if they are available for a quick chat."
    ]
    angle = random.choice(angles)
    
    prompt = (
        f"You are reaching out to a business owner on WhatsApp.\n"
        f"Business Name: {business}\n"
        "CRITICAL RULES:\n"
        "1. Write EXACTLY ONE short, friendly sentence. Keep it casual and natural.\n"
        "2. Start with a greeting that might include their business name (e.g., 'Hi {business},' or 'Hello!').\n"
        "3. Purely say hello, hope they have a good day, and ask if they can chat for a bit.\n"
        "4. NEVER pitch anything or ask technical questions yet.\n"
        "5. NEVER say you are an AI.\n"
        f"6. VARIATION DIRECTIVE: {angle}\n"
    )
    
    response = completion(
        model=config.LITELLM_MODEL,
        messages=[{"role": "user", "content": prompt}],
        max_tokens=60,
        temperature=0.7,
        stop=["###", "User:", "\n\n"]
    )
    
    msg = response.choices[0].message.content.strip()
    # Strip any accidental surrounding quotes generated by the LLM
    if msg.startswith('"') and msg.endswith('"'):
        msg = msg[1:-1]
    elif msg.startswith("'") and msg.endswith("'"):
        msg = msg[1:-1]
        
    return msg

def generate_reply(ticket: dict) -> str:
    import storage
    business = ticket.get("Business Name", "there")
    phone = ticket.get("Phone Number", "")
    
    try:
        kb = open("../data/knowledgebase.txt").read()
    except FileNotFoundError:
        kb = "Automated CRM and booking software."
        
    chat_history = storage.get_chat_history(phone)
    
    # We must construct a robust system prompt that acts as the persona
    sys_content = (
        f"{SYSTEM_PROMPT}\n\n"
        "TONE DIRECTIVE:\n"
        "You are a human technical consultant. Speak naturally and professionally. Be concise.\n\n"
        "BEHAVIORAL RULES:\n"
        "1. Do not act like a robot. Speak like a normal human texting on WhatsApp.\n"
        "2. If they just say 'hello' or test you, respond naturally without instantly forcing a sales pitch.\n"
        "3. Only ask them about their business operations if it flows naturally.\n\n"
        "1. Be conversational and polite. If they ask a casual question (like 'how are you'), answer it normally, but smoothly transition back to business.\n"
        "2. If the user asks for a discount, state exactly: 'Our architecture is priced based on recovered revenue. A single converted lead pays the monthly overhead. Are you currently tracking your after-hours lead drop-off rate?'\n"
        "3. Keep your sentences natural and professional. Do not be overly aggressive.\n"
        "4. If the user explicitly asks to speak to a human, or asks a complex technical question NOT covered in the knowledgebase, reply with EXACTLY the word: HANDOVER_REQUIRED\n\n"
        f"Client Context:\n"
        f"- Client Business Name: {business}\n"
        f"- What we do / Knowledgebase: {kb}\n"
    )
    
    messages = [{"role": "system", "content": sys_content}]
    
    # Pre-seed history with the "Bot Last Message" if chat_history is completely empty (for old leads)
    if not chat_history:
        old_bot_msg = ticket.get("Bot Last Message")
        if old_bot_msg and old_bot_msg != "Unknown":
            messages.append({"role": "assistant", "content": old_bot_msg})
        else:
            # We don't know what we said. Just seed a generic context
            sys_content += "\n(You contacted them earlier but the exact message was lost. Simply respond to their message naturally.)"
            messages[0]["content"] = sys_content
    else:
        messages.extend(chat_history)
        
    response = completion(
        model=config.LITELLM_MODEL,
        messages=messages,
        max_tokens=80,
        temperature=0.7,
        stop=["###", "User:", "\n\n"]
    )
    msg = response.choices[0].message.content.strip()
    if msg.startswith('"') and msg.endswith('"'):
        msg = msg[1:-1]
    elif msg.startswith("'") and msg.endswith("'"):
        msg = msg[1:-1]
        
    return msg

def evaluate_inbound(text: str) -> str:
    import re
    text_lower = text.lower()
    
    # 1. Instantly pass short human messages
    if len(text.split()) <= 4:
        return "VALID"
        
    # 2. Heuristics for auto-replies
    auto_reply_keywords = [
        "thank you for contacting", "welcome to", "business hours",
        "am to ", "pm", "हमारा पता", "location:", "maps.app.goo.gl",
        "press 1", "press 2", "for more details visit", "automated message"
    ]
    
    for kw in auto_reply_keywords:
        if kw in text_lower:
            return "AUTO_REPLY"
            
    # 3. Check for typical business hour formats like 9:00 AM - 6:00 PM
    if re.search(r'\d{1,2}\s*(am|pm)\s*to\s*\d{1,2}\s*(am|pm)', text_lower):
        return "AUTO_REPLY"
        
    # 4. Check if it's a massive block of text (often menus or promos)
    if len(text) > 300:
        return "AUTO_REPLY"
        
    return "VALID"
